# Title of the site
title: "About-me"
# Description of the site
description: "Portfolio theme"

# The subpath of your site - use "" if you're hosting a blog at the root level
baseurl: "/jekyll-about-me"
# The base hostname & protocol for your site
url: "jsidrach.github.io"

# Do not publish these files
exclude: ["README.md", "Gemfile", "Gemfile.lock", "LICENSE"]

# Sass configuration - compress resulting stylesheet
sass:
  style: compressed

# Navigation bar
navbar:
  - name: GitHub
    link: https://github.com/jsidrach/jekyll-about-me
    icon: repo.svg

  - name: LinkedIn
    link: https://linkedin.com/in/
    icon: jobs.svg

  - name: Resume
    link: /public/resume.pdf
    icon: resume.svg

  - name: Mail
    link: mailto:example@mail.com
    icon: mail.svg
